micronaut:
  application:
    name: micronautguide
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/todo
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
graphql:
  graphiql.enabled: true